# =============================================================================
# Hyprpaper Configuration
# =============================================================================

ipc = on
splash = false
